### ISSUE TITLE
Make test mode

### ISSUE THREAD

**Issue by TheMightyWarPig** [frc5687/2017-protobot#75]
Adds a mode to test all the various subsystems on the robot as well as get the sensor values for them

**Comment by BenBernardCIS** [comment]
For each actuator on the bot, we want a test command added to the FullSystemTest commandgroup.  Each would run the actuator in a prescribed way, and measure whatever sensors/inputs are avaialble to confirm that it behaved as expected.

For example, a TestDriveCIMCommand would take a victor port, a PDP port, and an encoder port.
The execute() method would run the CIM for a preset time and ensure that the PDP reports (roughly) the right amps draw and the the encode move in the right direction and (roughly) the right distance.

**Comment by BenBernardCIS** [comment]
So, it turns out my understanding of "test mode" in wpilib was somewhat off.  Okay, it was completely wrong.

Since that won't work for us, I think we should create a "test" autonomous, which is triggered by setting the rotary switches to a currently-unused combination, holding down a gamepad button (or perhaps two--the two unused mini buttons) and enabling autonomous mode.  This should allow us to reuse the existing test code with minimal modifications.
